<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netstandard2.0</TargetFrameworks>
  </PropertyGroup>
  <PropertyGroup Condition="'$(VersionNumber)' == ''">
    <VersionNumber>3.0-debug</VersionNumber>
  </PropertyGroup>
  <PropertyGroup>
    <PackageId>SanteDB.Messaging.IHE.MADX</PackageId>
    <Title>SanteDB MADX Messaging</Title>
    <Version>$(VersionNumber)</Version>
    <Description>Allows SanteDB iCDR to send MADX Messages.</Description>
    <Authors>SanteSuite Contributors</Authors>
    <PackageTags>SanteDB</PackageTags>
    <RepositoryUrl>https://github.com/santedb/santedb-madx</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <IncludeSymbols>true</IncludeSymbols>
    <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    <Product>SanteDB</Product>
    <Copyright>Copyright (C) 2015-2026 SanteSuite Contributors (See: NOTICES)</Copyright>
    <Company>SanteSuite Contributors</Company>
    <PackageIconUrl>http://santesuite.org/assets/img/logo.png</PackageIconUrl>
    <PackageProjectUrl>http://santesuite.org</PackageProjectUrl>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugSymbols>true</DebugSymbols>
    <DebugType>full</DebugType>
    <Optimize>false</Optimize>
    <OutputPath>..\bin\Debug\</OutputPath>
    <DocumentationFile>..\bin\Debug\SanteDB.Messaging.IHE.MADX.xml</DocumentationFile>
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <OutputPath>..\bin\Release\</OutputPath>
    <DocumentationFile>..\bin\Release\SanteDB.Messaging.IHE.MADX.xml</DocumentationFile>
    <DefineConstants>TRACE</DefineConstants>
    <ErrorReport>prompt</ErrorReport>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>
  
  <ItemGroup>
    <None Include="..\SanteDB.licenseheader">
      <Link>SanteDB.licenseheader</Link>
    </None>
    
  </ItemGroup>
  <Choose>
    <When Condition="$(SolutionName.Contains('-nuget'))">
      <ItemGroup>
        <PackageReference Include="SanteDB.Core.Api" Version="$(VersionNumber)" />
        <PackageReference Include="SanteDB.Core.Model" Version="$(VersionNumber)" />
      </ItemGroup>
    </When>
    <Otherwise>
      <ItemGroup>
        <ProjectReference Include="..\..\santedb-api\SanteDB.Core.Api\SanteDB.Core.Api.csproj" />
        <ProjectReference Include="..\..\santedb-model\SanteDB.Core.Model\SanteDB.Core.Model.csproj" />
      </ItemGroup>
    </Otherwise>
  </Choose>
  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json">
      <Version>13.0.3</Version>
    </PackageReference>
  </ItemGroup>
 

</Project>
